In [2]:
# PLEASE, DO NOT MODIFY THIS CELL!

# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np

# SECTION A data
nparr = np.arange(145, 217).reshape(12, 6)

# data location
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
a_df = pd.read_csv(data_url, header=0)
a_df.head()


iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

##  SECTION A

1. Determine the shape, number of dimensions and type of elements in the numpy array `nparr`
2. Determine the standard deviation of all elements in `nparr`
3. Determine the position (not the value) of the maximum value element in `nparr`
4. Create an array of the same shape as `nparr` but filled with zeros
5. Create an array of the same shape as `nparr` but filled with ones
6. Create an array of the same shape as `nparr` but where all elements are the square root values
7. Create an array result of shape `12` by `12` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`

In [3]:
# YOUR SECTION A ANSWER HERE (please use comments to number each of your answers)
#1.
nparr_shape = nparr.shape  #shape of nparr
print(f'Shape of nparr is {nparr_shape}')
print("Number of dimensions of nparr:", nparr.ndim)
print("Type of elements in nparr:", nparr.dtype)



Shape of nparr is (12, 6)
Number of dimensions of nparr: 2
Type of elements in nparr: int64


In [4]:
#2.
nparr_std_dev = np.std(nparr) #standard deviation of all the elements
print(f'standard deviation of all the elements {nparr_std_dev}')


standard deviation of all the elements 20.7826049057058


In [5]:
#3.
max_position = np.unravel_index(np.argmax(nparr), nparr.shape)
print("Position of maximum value in nparr:", max_position)




Position of maximum value in nparr: (11, 5)


In [6]:
#4.
zeros_array = np.zeros_like(nparr) #array with same shape as nparr but with zeroes
print('zeros array\n',zeros_array)



zeros array
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [7]:
#5.
ones_array = np.ones_like(nparr) #array with same shape as nparr but with ones

print("Ones array:\n", ones_array)



Ones array:
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [8]:
#6.
sqrt_array = np.sqrt(nparr)
print("Square root array:\n", sqrt_array)



Square root array:
 [[12.04159458 12.08304597 12.12435565 12.16552506 12.20655562 12.24744871]
 [12.28820573 12.32882801 12.36931688 12.40967365 12.4498996  12.489996  ]
 [12.52996409 12.56980509 12.60952021 12.64911064 12.68857754 12.72792206]
 [12.76714533 12.80624847 12.84523258 12.88409873 12.92284798 12.9614814 ]
 [13.         13.03840481 13.07669683 13.11487705 13.15294644 13.19090596]
 [13.22875656 13.26649916 13.3041347  13.34166406 13.37908816 13.41640786]
 [13.45362405 13.49073756 13.52774926 13.56465997 13.60147051 13.6381817 ]
 [13.67479433 13.7113092  13.74772708 13.78404875 13.82027496 13.85640646]
 [13.89244399 13.92838828 13.96424004 14.         14.03566885 14.07124728]
 [14.10673598 14.14213562 14.17744688 14.2126704  14.24780685 14.28285686]
 [14.31782106 14.35270009 14.38749457 14.4222051  14.45683229 14.49137675]
 [14.52583905 14.56021978 14.59451952 14.62873884 14.6628783  14.69693846]]


In [9]:
#7.
dot_array = np.dot(nparr, nparr.T) #dot product of npaar and transpose of nparr
print("Result of multiplication:\n", dot_array)

Result of multiplication:
 [[130555 135865 141175 146485 151795 157105 162415 167725 173035 178345
  183655 188965]
 [135865 141391 146917 152443 157969 163495 169021 174547 180073 185599
  191125 196651]
 [141175 146917 152659 158401 164143 169885 175627 181369 187111 192853
  198595 204337]
 [146485 152443 158401 164359 170317 176275 182233 188191 194149 200107
  206065 212023]
 [151795 157969 164143 170317 176491 182665 188839 195013 201187 207361
  213535 219709]
 [157105 163495 169885 176275 182665 189055 195445 201835 208225 214615
  221005 227395]
 [162415 169021 175627 182233 188839 195445 202051 208657 215263 221869
  228475 235081]
 [167725 174547 181369 188191 195013 201835 208657 215479 222301 229123
  235945 242767]
 [173035 180073 187111 194149 201187 208225 215263 222301 229339 236377
  243415 250453]
 [178345 185599 192853 200107 207361 214615 221869 229123 236377 243631
  250885 258139]
 [183655 191125 198595 206065 213535 221005 228475 235945 243415 250885
  258355 26

##  SECTION B

The dataframe `a_df` loads the dataset that contains information on a number of categories regarding traffic (variable `cnt` represents the actual traffic) at US airports from February 2011.
The dataset has already been loaded for you in the first code cell above.
 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than `10,000` (ideally, you should format the print to put the thousands comma separator--as in `23,400` instead of `23400`
 2. Print the names of all the columns of the dataframe
 3. Print a subset of the dataframe containing the `10th` and the `3rd` rows of the original dataframe (`in that order`).
 4. Which US `state` has the `8th` largest __total__ airport traffic? Please, make sure you use the correct variable as described above.
 5. Which state has the second-most __total__ number of airports (i.e. the second-most amount of airports)?
 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?
 7. What is the total airport traffic for all states that border the state of Massachusetts?


In [10]:
# YOUR SECTION B ANSWER HERE (please use comments to number each of your answers)
#1.
print(f"Q1. \nThe number of rows for the subset of the dataframe for which traffic values are higher than 10,000 is {len(a_df[a_df['cnt']>10000])}\n")

Q1. 
The number of rows for the subset of the dataframe for which traffic values are higher than 10,000 is 10



In [11]:
#2.
print(f'Q2. \nThe name of columns are:{list(a_df.columns)}\n')

Q2. 
The name of columns are:['iata', 'airport', 'city', 'state', 'country', 'lat', 'long', 'cnt']



In [12]:
#3.
print(f'Q3.Subset with 10th and 3rd rows will be \n\n ', a_df.iloc[[10,3]])

Q3.Subset with 10th and 3rd rows will be 

     iata                           airport            city state country  \
10  SLC               Salt Lake City Intl  Salt Lake City    UT     USA   
3   PHX  Phoenix Sky Harbor International         Phoenix    AZ     USA   

          lat        long    cnt  
10  40.788388 -111.977773   9898  
3   33.434167 -112.008056  17290  


In [13]:
#4.
df_cnt = a_df.groupby(by=['state']).sum(numeric_only=True) #grouping by state
df_cnt_sorted = df_cnt.sort_values(by=['cnt'],ascending=False) #sorting in descending order
df_cnt_sorted.reset_index(inplace=True) #reset the index
print(f'\nQ4.\nThe state with 8th largest total airport traffic is:{df_cnt_sorted["state"][7]}')


Q4.
The state with 8th largest total airport traffic is:CO


In [14]:
#5.
df_groupby_state = a_df.groupby(by=['state'])
df_count = df_groupby_state['airport'].count().sort_values(ascending=False).reset_index()
print(f'\nQ5.\n The state with second-most total number of airports (i.e. the second-most amount of airports) is {df_count["state"][1]}')


Q5.
 The state with second-most total number of airports (i.e. the second-most amount of airports) is TX


In [15]:
#6.
df_count_sum = a_df.groupby(['city']).agg({'airport':'count','cnt':'sum'}).sort_values(by='cnt') #agrregating by air port count, and sum of traffic, sorting by cnt
df_more_than_one_airport = df_count_sum[df_count_sum['airport']>1].reset_index()  #filter city with more airports
print(f"\nQ6.\n Of the cities that have multiple airports, one that has the least total traffic for all airports is {df_more_than_one_airport['city'][0]}")


Q6.
 Of the cities that have multiple airports, one that has the least total traffic for all airports is Charleston


In [16]:
#7.
neighbour_states=a_df[(a_df['state']=='NY') | (a_df['state']=='VT') | (a_df['state']=='NH') | (a_df['state']=='RI') | (a_df['state']=='CT')]
print(f"\nQ7.\n Total airport traffic for all states that border the state of Massachusetts {neighbour_states['cnt'].sum()}")


Q7.
 Total airport traffic for all states that border the state of Massachusetts 22007


In [17]:
city_traffic = a_df.groupby('city')['cnt'].sum()

# get cities with multiple airports
multi_airports = city_traffic[city_traffic.duplicated(keep=False)].index

In [18]:
multi_airports

Index(['Alexandria', 'Appleton', 'Augusta', 'Bellingham', 'Bismarck', 'Casper',
       'Charlottesville', 'Chattanooga', 'Cheyenne', 'Cody',
       'Columbus-Starkville-West Point', 'Dubuque', 'Eau Claire', 'Evansville',
       'Fayetteville', 'Fort Smith', 'Fresno', 'Gillette', 'Great Falls',
       'Gunnison', 'Helena', 'Hollister', 'Idaho Falls', 'Klamath Falls',
       'Lewisburg', 'Mammoth Lakes', 'Manhattan', 'McAllen', 'Medford',
       'Meridian', 'New Bern', 'North Bend', 'Oklahoma City', 'Paducah',
       'Pasco', 'Peoria', 'Pocatello', 'Redding', 'Reno', 'Rock Springs',
       'San Luis Obispo', 'Santa Fe', 'Santa Maria', 'Shreveport', 'Telluride',
       'Valdosta', 'Valparaiso', 'Wichita Falls', 'Wilkes-Barre/Scranton'],
      dtype='object', name='city')